[package]
name = "test_res"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable = "0.10.0"
csv = "1.2.2"
rand = "0.8.5"