// RUST is designed for lower level system's programming unlike Python which is a higher level language.
//mod challenge01;
//mod compound_datatypes;
//mod function_sim;
// mod challenge02;
//mod program_flow_control;
//mod challenge03;
//mod basics;
//mod challenge03;
//mod ownership_scope;
//mod references;
//mod modules;
//mod challenge04;

//mod challenge05;
//mod cli_io;
//mod file_ops;
//mod challenge06_cli_version;
//mod challenge06;
//mod struct_sim;
//mod challenge07;
//mod challenge07_circle;
//mod generic_type;
//mod challenge08;
//mod traits_sim;
//mod trait_bound_sim;
//mod challenge09;
//mod lifetimes_sim;
//mod lifetimes_struct_sim;
//mod enum_sim;
//mod challenge10;
//mod error_handling_sim;
//mod challenge11;
mod basics;

fn main() {
    println!("Rust Playbook and Simulations\n----------------------------");
    //challenge01::challenge();
    //compound_datatypes::compound_datatype();
    //function_sim::function_sim();
    //challenge02::challenge();
    //program_flow_control::simulation();
    //challenge03::challenge();
    //ownership_scope::simulation();
    //references::simulation();
    //challenge04::challenge();
    //modules::simulation();
    //challenge05::challenge();
    //cli_io::simulation();
    //file_ops::simulation();
    //challenge06::challenge();
    //challenge06_cli_version::challenge();
    //struct_sim::simulation();
    //challenge07::challenge();
    //challenge07_circle::challenge();
    //generic_type::simulation();
    //challenge08::challenge();
    //traits_sim::simulation();
    //trait_bound_sim::simulation();
    //challenge09::challenge();
    //lifetimes_sim::simulation();
    //lifetimes_struct_sim::simulation();
    //enum_sim::simulation();
    //challenge10::challenge();
    //error_handling_sim::simulation();
    //challenge11::challenge();
    basics::simulation();
}
